set schema anytime;

INSERT INTO CAMPAIGN (NAME, COUPON_ID, LAYOUT_ID, PERCENTAGE, VOLUME, DESCRIPTION, DISCOUNT_TITLE, COUPON_VALIDATION_CLASS, COUPON_VALIDATION_PATTERN, ICON_PATH)
VALUES ('MOTOR_RETARGETING_0409', 2264, 1, 5, 1, 'MOTOR RETARGETING (ΠΕΛΑΤΕΣ) - Έκπτωση 5%','SAVE 5', 'gr.anytime.service.campaign.impl.LuhnCouponPolicy', '^10022640000((([0]{1}[0-9]{1}|[1]{1}[0-4]{1})[0-9]{3})|15006)$', '/resources/logos/motor-retargeting-5.png');
INSERT INTO PRODUCT_LINE_CAMPAIGN (PRODUCT_LINE_KEY, CAMPAIGN_NAME) (SELECT PL.STRATEGY_KEY, 'MOTOR_RETARGETING_0409' FROM PRODUCT_LINE PL WHERE PL.STRATEGY_KEY IN ('MOTOR','BTM','SMART_DRIVE'));

INSERT INTO CAMPAIGN (NAME, COUPON_ID, LAYOUT_ID, PERCENTAGE, VOLUME, DESCRIPTION, DISCOUNT_TITLE, COUPON_VALIDATION_CLASS, COUPON_VALIDATION_PATTERN, ICON_PATH)
VALUES ('MOTOR_RETARGETING_1109', 2265, 1, 5, 1, 'MOTOR RETARGETING (ΠΕΛΑΤΕΣ) - Έκπτωση 5%','SAVE 5', 'gr.anytime.service.campaign.impl.LuhnCouponPolicy', '^10022650000((([0]{1}[0-9]{1}|[1]{1}[0-4]{1})[0-9]{3})|15003)$', '/resources/logos/motor-retargeting-5.png');
INSERT INTO PRODUCT_LINE_CAMPAIGN (PRODUCT_LINE_KEY, CAMPAIGN_NAME) (SELECT PL.STRATEGY_KEY, 'MOTOR_RETARGETING_1109' FROM PRODUCT_LINE PL WHERE PL.STRATEGY_KEY IN ('MOTOR','BTM','SMART_DRIVE'));

INSERT INTO CAMPAIGN (NAME, COUPON_ID, LAYOUT_ID, PERCENTAGE, VOLUME, DESCRIPTION, DISCOUNT_TITLE, COUPON_VALIDATION_CLASS, COUPON_VALIDATION_PATTERN, ICON_PATH)
VALUES ('MOTOR_RETARGETING_1809', 2266, 1, 5, 1, 'MOTOR RETARGETING (ΠΕΛΑΤΕΣ) - Έκπτωση 5%','SAVE 5', 'gr.anytime.service.campaign.impl.LuhnCouponPolicy', '^10022660000((([0]{1}[0-9]{1}|[1]{1}[0-4]{1})[0-9]{3})|15001)$', '/resources/logos/motor-retargeting-5.png');
INSERT INTO PRODUCT_LINE_CAMPAIGN (PRODUCT_LINE_KEY, CAMPAIGN_NAME) (SELECT PL.STRATEGY_KEY, 'MOTOR_RETARGETING_1809' FROM PRODUCT_LINE PL WHERE PL.STRATEGY_KEY IN ('MOTOR','BTM','SMART_DRIVE'));

INSERT INTO CAMPAIGN (NAME, COUPON_ID, LAYOUT_ID, PERCENTAGE, VOLUME, DESCRIPTION, DISCOUNT_TITLE, COUPON_VALIDATION_CLASS, COUPON_VALIDATION_PATTERN, ICON_PATH)
VALUES ('MOTOR_RETARGETING_2509', 2267, 1, 5, 1, 'MOTOR RETARGETING (ΠΕΛΑΤΕΣ) - Έκπτωση 5%','SAVE 5', 'gr.anytime.service.campaign.impl.LuhnCouponPolicy', '^10022670000((([0]{1}[0-9]{1}|[1]{1}[0-4]{1})[0-9]{3})|15009)$', '/resources/logos/motor-retargeting-5.png');
INSERT INTO PRODUCT_LINE_CAMPAIGN (PRODUCT_LINE_KEY, CAMPAIGN_NAME) (SELECT PL.STRATEGY_KEY, 'MOTOR_RETARGETING_2509' FROM PRODUCT_LINE PL WHERE PL.STRATEGY_KEY IN ('MOTOR','BTM','SMART_DRIVE'));

INSERT INTO CAMPAIGN (NAME, COUPON_ID, LAYOUT_ID, PERCENTAGE, VOLUME, DESCRIPTION, DISCOUNT_TITLE, COUPON_VALIDATION_CLASS, COUPON_VALIDATION_PATTERN, ICON_PATH)
VALUES ('MOTOR_RETARGETING_0210', 2268, 1, 5, 1, 'MOTOR RETARGETING (ΠΕΛΑΤΕΣ) - Έκπτωση 5%','SAVE 5', 'gr.anytime.service.campaign.impl.LuhnCouponPolicy', '^10022680000((([0]{1}[0-9]{1}|[1]{1}[0-4]{1})[0-9]{3})|15007)$', '/resources/logos/motor-retargeting-5.png');
INSERT INTO PRODUCT_LINE_CAMPAIGN (PRODUCT_LINE_KEY, CAMPAIGN_NAME) (SELECT PL.STRATEGY_KEY, 'MOTOR_RETARGETING_0210' FROM PRODUCT_LINE PL WHERE PL.STRATEGY_KEY IN ('MOTOR','BTM','SMART_DRIVE'));

INSERT INTO CAMPAIGN (NAME, COUPON_ID, LAYOUT_ID, PERCENTAGE, VOLUME, DESCRIPTION, DISCOUNT_TITLE, COUPON_VALIDATION_CLASS, COUPON_VALIDATION_PATTERN, ICON_PATH)
VALUES ('MOTOR_RETARGETING_0910', 2269, 1, 5, 1, 'MOTOR RETARGETING (ΠΕΛΑΤΕΣ) - Έκπτωση 5%','SAVE 5', 'gr.anytime.service.campaign.impl.LuhnCouponPolicy', '^10022690000((([0]{1}[0-9]{1}|[1]{1}[0-4]{1})[0-9]{3})|15005)$', '/resources/logos/motor-retargeting-5.png');
INSERT INTO PRODUCT_LINE_CAMPAIGN (PRODUCT_LINE_KEY, CAMPAIGN_NAME) (SELECT PL.STRATEGY_KEY, 'MOTOR_RETARGETING_0910' FROM PRODUCT_LINE PL WHERE PL.STRATEGY_KEY IN ('MOTOR','BTM','SMART_DRIVE'));

INSERT INTO CAMPAIGN (NAME, COUPON_ID, LAYOUT_ID, PERCENTAGE, VOLUME, DESCRIPTION, DISCOUNT_TITLE, COUPON_VALIDATION_CLASS, COUPON_VALIDATION_PATTERN, ICON_PATH)
VALUES ('MOTOR_RETARGETING_1610', 2270, 1, 5, 1, 'MOTOR RETARGETING (ΠΕΛΑΤΕΣ) - Έκπτωση 5%','SAVE 5', 'gr.anytime.service.campaign.impl.LuhnCouponPolicy', '^10022700000((([0]{1}[0-9]{1}|[1]{1}[0-4]{1})[0-9]{3})|15003)$', '/resources/logos/motor-retargeting-5.png');
INSERT INTO PRODUCT_LINE_CAMPAIGN (PRODUCT_LINE_KEY, CAMPAIGN_NAME) (SELECT PL.STRATEGY_KEY, 'MOTOR_RETARGETING_1610' FROM PRODUCT_LINE PL WHERE PL.STRATEGY_KEY IN ('MOTOR','BTM','SMART_DRIVE'));

INSERT INTO CAMPAIGN (NAME, COUPON_ID, LAYOUT_ID, PERCENTAGE, VOLUME, DESCRIPTION, DISCOUNT_TITLE, COUPON_VALIDATION_CLASS, COUPON_VALIDATION_PATTERN, ICON_PATH)
VALUES ('MOTOR_RETARGETING_2310', 2271, 1, 5, 1, 'MOTOR RETARGETING (ΠΕΛΑΤΕΣ) - Έκπτωση 5%','SAVE 5', 'gr.anytime.service.campaign.impl.LuhnCouponPolicy', '^10022710000((([0]{1}[0-9]{1}|[1]{1}[0-4]{1})[0-9]{3})|15001)$', '/resources/logos/motor-retargeting-5.png');
INSERT INTO PRODUCT_LINE_CAMPAIGN (PRODUCT_LINE_KEY, CAMPAIGN_NAME) (SELECT PL.STRATEGY_KEY, 'MOTOR_RETARGETING_2310' FROM PRODUCT_LINE PL WHERE PL.STRATEGY_KEY IN ('MOTOR','BTM','SMART_DRIVE'));

INSERT INTO CAMPAIGN (NAME, COUPON_ID, LAYOUT_ID, PERCENTAGE, VOLUME, DESCRIPTION, DISCOUNT_TITLE, COUPON_VALIDATION_CLASS, COUPON_VALIDATION_PATTERN, ICON_PATH)
VALUES ('MOTOR_RETARGETING_3010', 2272, 1, 5, 1, 'MOTOR RETARGETING (ΠΕΛΑΤΕΣ) - Έκπτωση 5%','SAVE 5', 'gr.anytime.service.campaign.impl.LuhnCouponPolicy', '^10022720000((([0]{1}[0-9]{1}|[1]{1}[0-4]{1})[0-9]{3})|15009)$', '/resources/logos/motor-retargeting-5.png');
INSERT INTO PRODUCT_LINE_CAMPAIGN (PRODUCT_LINE_KEY, CAMPAIGN_NAME) (SELECT PL.STRATEGY_KEY, 'MOTOR_RETARGETING_3010' FROM PRODUCT_LINE PL WHERE PL.STRATEGY_KEY IN ('MOTOR','BTM','SMART_DRIVE'));
